version: "3"

tasks:
  generate-claude-settings:
    desc: Generate claude settings.json from jsonnet
    cmds:
      - jsonnet dot_claude/settings.jsonnet > dot_claude/settings.json
      - jsonnet dot_claude/.mcp.jsonnet > dot_claude/.mcp.json
    sources:
      - dot_claude/settings.jsonnet
      - dot_claude/.mcp.jsonnet
    generates:
      - dot_claude/settings.json
      - dot_claude/.mcp.json

  generate:
    desc: Generate all json files from jsonnet
    deps:
      - generate-claude-settings
