# Taskfile.yaml - 自動生成ファイルの一元管理
#
# 目的:
#   - mise.lock, aqua-checksums, mise bootstrap などの自動生成ファイルを
#     統一的なコマンドで管理できるようにする
#   - ローカル開発と CI で同じタスクを使用し、一貫性を保つ
#
# 使い方:
#   task              # 全ての自動生成を実行
#   task lock         # lockfiles/checksums/bootstrap のみ
#   task generate     # (No-op) JSON 生成は chezmoi に移行
#   task check        # CI 用: 生成後に diff チェック（mise.lock, JSON 除外）
#
# 注意:
#   - mise.lock は実行環境（macOS/Linux）によって結果が異なる既知の問題があるため、
#     CI での diff チェックからは除外している
#   - mise.lock の更新は Renovate ワークフロー（mise-lock.yaml）に任せる
#   - JSON 生成は chezmoi apply 時に run_onchange スクリプトで実行される
#
# 参考:
#   - https://taskfile.dev/
#   - https://mise.jdx.dev/dev-tools/mise-lock.html

version: "3"

# root: true により、サブディレクトリからも task コマンドを実行可能
root: true

# checksum 方式でキャッシュ管理（ファイル内容が変わった時のみ再実行）
method: checksum

vars:
  # 設定ファイルのディレクトリパス
  MISE_CONFIG_DIR: dot_config/mise
  AQUA_CONFIG_DIR: dot_config/aquaproj-aqua
  # mise lock で対象とするプラットフォーム
  # 全プラットフォームを明示的に指定することで、実行環境に関係なく同じ結果を得る
  MISE_PLATFORMS: linux-x64,linux-arm64,macos-x64,macos-arm64,windows-x64

tasks:
  #############################################################################
  # Default: 全タスク実行
  #############################################################################
  default:
    desc: Run all generation tasks
    deps:
      - generate
      - lock

  #############################################################################
  # jsonnet 生成 (No-op)
  # JSON 生成は chezmoi apply 時に run_onchange_after_generate-jsonnet.sh.tmpl で実行
  # default タスクとの依存関係を維持するために残している
  #############################################################################
  generate:
    desc: (No-op) JSON generation moved to chezmoi
    cmds:
      - echo "JSON generation is now handled by chezmoi apply"

  #############################################################################
  # mise.lock 生成
  # ツールのバージョンと checksum を固定して再現性を確保
  # -p オプションで全プラットフォームを指定（環境差異を防ぐ）
  # rm -f で古い lockfile を削除してから再生成（古いエントリが残る問題を回避）
  #############################################################################
  mise:lock:root:
    desc: Update root mise.lock
    cmds:
      - rm -f mise.lock && mise lock -p {{.MISE_PLATFORMS}}
    sources:
      - .mise.toml
    generates:
      - mise.lock

  mise:lock:config:
    desc: Update dot_config/mise/mise.lock
    dir: "{{.MISE_CONFIG_DIR}}"
    cmds:
      - rm -f mise.lock && mise lock -p {{.MISE_PLATFORMS}}
    sources:
      - config.toml
    generates:
      - mise.lock

  mise:lock:
    desc: Update all mise lockfiles
    deps:
      - mise:lock:root
      - mise:lock:config

  #############################################################################
  # aqua checksum 生成
  # mise lock で checksum が取得できないツール（aws-cli, 1password/cli, zoxide）用
  # --prune で不要なエントリを削除
  #############################################################################
  aqua:checksum:
    desc: Update aqua checksums
    dir: "{{.AQUA_CONFIG_DIR}}"
    cmds:
      - aqua update-checksum --prune
    sources:
      - aqua.yaml
    generates:
      - aqua-checksums.json

  #############################################################################
  # mise bootstrap 生成
  # mise 自体をインストールするためのスクリプトを生成
  # .mise-bootstrap-version のバージョンを -V オプションで明示的に指定
  #############################################################################
  mise:bootstrap:
    desc: Update mise bootstrap script
    cmds:
      - |
        source .mise-bootstrap-version
        VERSION="${MISE_VERSION#v}"
        mise generate bootstrap -V "$VERSION" -w ./dot_local/bin/executable_mise
    sources:
      - .mise-bootstrap-version
    generates:
      - dot_local/bin/executable_mise

  #############################################################################
  # 統合タスク
  # lock 系のタスクをまとめて実行
  #############################################################################
  lock:
    desc: Update all lockfiles, checksums, and bootstrap
    deps:
      - mise:lock
      - aqua:checksum
      - mise:bootstrap

  #############################################################################
  # CI 用チェックタスク
  # 自動生成ファイルが最新かどうかを検証
  #
  # 注意: mise.lock は実行環境（macOS/Linux）によって結果が異なる既知の問題があるため、
  # diff チェックから除外している。mise.lock の更新は Renovate ワークフローに任せる。
  # 参考: https://github.com/jdx/mise/discussions/6942
  #############################################################################
  check:
    desc: Check if generated files (except mise.lock) are up-to-date
    cmds:
      - task: aqua:checksum
        vars: {}
      - task: mise:bootstrap
        vars: {}
      - |
        # mise.lock は実行環境によって差異が出るため除外
        # JSON 生成は chezmoi に移行したため除外
        # aqua-checksums, bootstrap のみチェック
        CHECK_FILES="dot_config/aquaproj-aqua/aqua-checksums.json dot_local/bin/executable_mise"
        if ! git diff --quiet -- $CHECK_FILES; then
          echo "Error: Generated files are out of date. Run 'task' locally and commit the changes."
          git diff --name-only -- $CHECK_FILES
          git diff -- $CHECK_FILES
          exit 1
        fi
        echo "All generated files are up-to-date."
