{
  ['$schema']: 'https://raw.githubusercontent.com/tak848/ccgate/main/ccgate.schema.json',
  provider: {
    name: 'anthropic',
    model: 'claude-haiku-4-5',
    timeout_ms: 10000,
  },
  allow: [
    'Read-Only Operations: GET requests, read-only API calls, or queries that do not modify state.',
    'Local Operations: Read-only work inside the current repository or current worktree.',
    'Library Source Read: Read-only inspection (Read/Glob/Grep, or Bash head/tail/sed -n/cat/less/file/stat/wc/awk) of package and module caches and of system temp. This includes: Go module cache (~/go/pkg/mod, $GOPATH/pkg/mod, ~/Library/Caches/go-build), node package manager stores (pnpm/npm/yarn caches), Python package cache, cargo registry (~/.cargo/registry), Homebrew prefix (/opt/homebrew, /usr/local), ~/.cache/*, /usr/include, system temp (/tmp, /var/folders), and installed tool binaries. These cannot contain user private source repos. This rule is READ-ONLY file access only — any write, delete, or execute (including running an installed binary) MUST fallthrough.',
    'Draft PR Creation: If the operation creates a pull request AND draft is true in tool_input_raw, allow immediately. If draft is false or absent, fallthrough. Marking an existing draft PR as ready-for-review, converting non-draft → draft, updating the title/body of an existing PR, or pushing commits to a PR branch the agent did not create in this session all require user confirmation — fallthrough.',
    'Local Development: Project-declared build/test/lint/format scripts invoked via the project\'s own task runner — e.g. `pnpm run <script>`, `uv run <script>`, `cargo test`, `go test`, `make <target>` — where the target is visibly a build/test/lint/format step and does NOT chain into deploys, migrations, or network writes to shared systems. Arbitrary scripts (e.g. `make deploy`, `pnpm run build:prod`, `pytest tests/integration/ --prod-db`, `./scripts/seed-staging.sh`) MUST fallthrough even if declared in a manifest; deploy / migration / prod-target scripts require explicit user intent.',
    'Git Feature Branch: Git operations on non-protected branches. Protected branches include the default branch (main, master) and long-lived deployment branches (release/*, releases/*, hotfix/*, deploy/*, env/*, prod, production, stg, staging, or similarly named branches whose semantics indicate deployment / environment / release targeting).',
    'Package Manager Install: Package manager install/sync commands in the current repository that DO NOT install agent-chosen package names — e.g. `pnpm install`, `uv sync`, `cargo build`, `bundle install`. `go mod tidy` is allowed as a normalisation step when the agent has not added new imports in this session; if new imports were added, `go mod tidy` introduces new dependencies and MUST fallthrough. Agent-chosen installations (`pnpm add foo`, `uv add bar`, `go get <pkg>`) MUST fallthrough.',
  ],
  deny: [
    'Git Destructive: force push (--force), deleting remote branches (push --delete), or rewriting published history. Check recent_transcript and tool_input.description — if the user explicitly requested the operation, fallthrough instead of deny. deny_message: Destructive git operation. Confirm explicit user instruction.',
    'Sibling Checkout Access (ABSOLUTE): When is_worktree is true, ANY access (read or write, via any tool, no exceptions) to paths under primary_checkout_root or under other sibling worktree checkouts of the SAME repository MUST be denied. ABSOLUTE means this is NOT cleared by in-session user authorization — if sibling-worktree access is genuinely needed, the user must restart the session with --add-dir targeting that path. This rule is strictly about same-repo cross-checkout confusion — it does NOT apply to package/module caches, /tmp, or unrelated repositories (those are handled by other rules). deny_message: Accessing another checkout of the same repository is forbidden. Stay within this worktree.',
    'Unrelated Repository Access: Reading or writing files inside a DIFFERENT git repository the user has NOT explicitly authorized via --add-dir. A path under ~/repos/*, ~/projects/*, ~/src/*, ~/work/*, ~/code/*, ~/ghq/* (or any path outside repo_root that is itself inside a git repository) should be denied when it is NOT a package/module cache — these look like user source repos. This applies even when reached via `cd` earlier in the session; detection is against the actual path touched by each action, not the current working directory alone. If the path is clearly a package/module cache or /tmp, this rule does NOT apply and the operation should fall through to Library Source Read. When genuinely uncertain whether a path is a private repo or a cache, fallthrough (not deny). deny_message: Reading outside authorized repositories. Ask the user to --add-dir this path if intentional.',
    'Direct Tool Invocation: Running tools via one-shot or ad-hoc package runners that fetch and execute code outside the declared manifest — e.g. `npx`, `pnpx`, `pnpm dlx`, `bunx`, `uvx`, `uv tool run`, or `go run <remote-path>` such as `go run github.com/foo/bar@latest`. Rationale: one-shot runners fetch and execute code not pinned by the repo\'s manifest. `pnpm exec <bin>` is also denied even when the binary is a declared devDependency — wrap it in a `pnpm run <script>` entry instead. deny_message: Direct tool invocation not allowed. Use project-defined scripts.',
    'Download and Execute: Piping downloaded content to a shell (curl|bash, wget|sh, etc.), or executing remote scripts without review. deny_message: Download-and-execute not allowed.',
    'Out-of-Repo Deletion: rm -rf or destructive file operations targeting paths outside the current repository (check referenced_paths against repo_root). Deletion within the repository (node_modules, dist, build artifacts) is fine. deny_message: Deletion outside repository not allowed.',
  ],
  environment: [
    '**Trusted repo**: The git repository the session started in.',
    '**Current worktree context**: Sibling worktrees of the same repository are off-limits by default — see the "Sibling Checkout Access (ABSOLUTE)" deny rule. The current worktree and its own files are the only in-scope area; do not fall back to primary checkout or sibling worktrees for reference material.',
  ],
}
